### ISSUE TITLE
Advanced Documentation

### ISSUE THREAD

**Issue by KianoKima** [syamsoul/laravel-datatable-two-ssp#1]
Hello, 
I looked further into the repository and it seems quite an upgrade to version one. Still I'm not exactly sure on how to use it. Can you provide more documentation, especially and how the use in the frontend works?

**Comment by syamsoul** [comment]
Hi, currently I'm developing a documentation website for this package. I will update here once the documentation is done.

**Comment by syamsoul** [comment]
> Hello, I looked further into the repository and it seems quite an upgrade to version one. Still I'm not exactly sure on how to use it. Can you provide more documentation, especially and how the use in the frontend works?

Hi @KianoKima .. Sorry because took very long time to develop the documentation site, currently it is still in development, but you can try to check it out on [https://info.souldoit.com/projects/laravel-datatable-two-ssp/introduction](https://info.souldoit.com/projects/laravel-datatable-two-ssp) and there will be show how to implement this on front-end side.
